import type { AppTextVariant, AppTextWeight } from "../../components/ui/AppText";

export interface TypographySpecimen {
  id: string;
  category: string;
  name: string;
  variant: AppTextVariant;
  weight?: AppTextWeight;
  family: string;
  weightLabel: string;
  size: string;
  lineHeight: string;
  letterSpacing: string;
  notes?: string;
}

/** Catalog of all 60 CADS text styles for the typography sandbox. */
export const TYPOGRAPHY_SPECIMENS: TypographySpecimen[] = [
  // Heading H1
  {
    id: "heading-h1-bold",
    category: "Heading",
    name: "Heading 1 / Bold",
    variant: "heading-h1",
    weight: "bold",
    family: "Space Grotesk",
    weightLabel: "Bold (700)",
    size: "48px",
    lineHeight: "52px",
    letterSpacing: "−1%",
  },
  {
    id: "heading-h1-semibold",
    category: "Heading",
    name: "Heading 1 / Semi Bold",
    variant: "heading-h1",
    weight: "semibold",
    family: "Space Grotesk",
    weightLabel: "Medium (500)",
    size: "48px",
    lineHeight: "52px",
    letterSpacing: "−1%",
    notes: "Figma Semi Bold → Medium on Space Grotesk",
  },
  {
    id: "heading-h1-regular",
    category: "Heading",
    name: "Heading 1 / Regular",
    variant: "heading-h1",
    weight: "regular",
    family: "Space Grotesk",
    weightLabel: "Regular (400)",
    size: "48px",
    lineHeight: "52px",
    letterSpacing: "−1%",
  },
  // Heading H2
  {
    id: "heading-h2-bold",
    category: "Heading",
    name: "Heading 2 / Bold",
    variant: "heading-h2",
    weight: "bold",
    family: "Space Grotesk",
    weightLabel: "Bold (700)",
    size: "38px",
    lineHeight: "40px",
    letterSpacing: "−1%",
  },
  {
    id: "heading-h2-semibold",
    category: "Heading",
    name: "Heading 2 / Semi Bold",
    variant: "heading-h2",
    weight: "semibold",
    family: "Space Grotesk",
    weightLabel: "Medium (500)",
    size: "38px",
    lineHeight: "40px",
    letterSpacing: "−1%",
  },
  {
    id: "heading-h2-regular",
    category: "Heading",
    name: "Heading 2 / Regular",
    variant: "heading-h2",
    weight: "regular",
    family: "Space Grotesk",
    weightLabel: "Regular (400)",
    size: "38px",
    lineHeight: "40px",
    letterSpacing: "−1%",
  },
  // Heading H3
  {
    id: "heading-h3-bold",
    category: "Heading",
    name: "Heading 3 / Bold",
    variant: "heading-h3",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "28px",
    lineHeight: "36px",
    letterSpacing: "0",
  },
  {
    id: "heading-h3-semibold",
    category: "Heading",
    name: "Heading 3 / Semi Bold",
    variant: "heading-h3",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "28px",
    lineHeight: "36px",
    letterSpacing: "0",
  },
  {
    id: "heading-h3-regular",
    category: "Heading",
    name: "Heading 3 / Regular",
    variant: "heading-h3",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "28px",
    lineHeight: "36px",
    letterSpacing: "0",
  },
  // Heading H4
  {
    id: "heading-h4-bold",
    category: "Heading",
    name: "Heading 4 / Bold",
    variant: "heading-h4",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "24px",
    lineHeight: "32px",
    letterSpacing: "0",
  },
  {
    id: "heading-h4-semibold",
    category: "Heading",
    name: "Heading 4 / Semi Bold",
    variant: "heading-h4",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "24px",
    lineHeight: "32px",
    letterSpacing: "0",
  },
  {
    id: "heading-h4-regular",
    category: "Heading",
    name: "Heading 4 / Regular",
    variant: "heading-h4",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "24px",
    lineHeight: "32px",
    letterSpacing: "0",
  },
  // Heading H5
  {
    id: "heading-h5-bold",
    category: "Heading",
    name: "Heading 5 / Bold",
    variant: "heading-h5",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "22px",
    lineHeight: "30px",
    letterSpacing: "0",
  },
  {
    id: "heading-h5-semibold",
    category: "Heading",
    name: "Heading 5 / Semi Bold",
    variant: "heading-h5",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "22px",
    lineHeight: "30px",
    letterSpacing: "0",
  },
  {
    id: "heading-h5-regular",
    category: "Heading",
    name: "Heading 5 / Regular",
    variant: "heading-h5",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "22px",
    lineHeight: "30px",
    letterSpacing: "0",
  },
  // Heading H6
  {
    id: "heading-h6-bold",
    category: "Heading",
    name: "Heading 6 / Bold",
    variant: "heading-h6",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "20px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  {
    id: "heading-h6-semibold",
    category: "Heading",
    name: "Heading 6 / Semi Bold",
    variant: "heading-h6",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "20px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  {
    id: "heading-h6-regular",
    category: "Heading",
    name: "Heading 6 / Regular",
    variant: "heading-h6",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "20px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  // Body
  {
    id: "body-1-bold",
    category: "Body",
    name: "Body 1 / Bold",
    variant: "body-1",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  {
    id: "body-1-semibold",
    category: "Body",
    name: "Body 1 / Semi Bold",
    variant: "body-1",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  {
    id: "body-1-regular",
    category: "Body",
    name: "Body 1 / Regular",
    variant: "body-1",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
  },
  {
    id: "body-2-bold",
    category: "Body",
    name: "Body 2 / Bold",
    variant: "body-2",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
  },
  {
    id: "body-2-semibold",
    category: "Body",
    name: "Body 2 / Semi Bold",
    variant: "body-2",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
  },
  {
    id: "body-2-regular",
    category: "Body",
    name: "Body 2 / Regular",
    variant: "body-2",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
  },
  {
    id: "body-3-bold",
    category: "Body",
    name: "Body 3 / Bold",
    variant: "body-3",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
  },
  {
    id: "body-3-semibold",
    category: "Body",
    name: "Body 3 / Semi Bold",
    variant: "body-3",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
  },
  {
    id: "body-3-regular",
    category: "Body",
    name: "Body 3 / Regular",
    variant: "body-3",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
  },
  {
    id: "body-4-bold",
    category: "Body",
    name: "Body 4 / Bold",
    variant: "body-4",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
  },
  {
    id: "body-4-semibold",
    category: "Body",
    name: "Body 4 / Semi Bold",
    variant: "body-4",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
  },
  {
    id: "body-4-regular",
    category: "Body",
    name: "Body 4 / Regular",
    variant: "body-4",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
  },
  {
    id: "body-5-bold",
    category: "Body",
    name: "Body 5 / Bold",
    variant: "body-5",
    weight: "bold",
    family: "Geist",
    weightLabel: "Bold (700)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
  },
  {
    id: "body-5-semibold",
    category: "Body",
    name: "Body 5 / Semi Bold",
    variant: "body-5",
    weight: "semibold",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
  },
  {
    id: "body-5-regular",
    category: "Body",
    name: "Body 5 / Regular",
    variant: "body-5",
    weight: "regular",
    family: "Geist",
    weightLabel: "Regular (400)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
  },
  // Overline
  {
    id: "overline-1",
    category: "Overline",
    name: "Overline 1",
    variant: "overline-1",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "+8%",
    notes: "UPPERCASE",
  },
  {
    id: "overline-2",
    category: "Overline",
    name: "Overline 2",
    variant: "overline-2",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "+8%",
    notes: "UPPERCASE",
  },
  {
    id: "overline-3",
    category: "Overline",
    name: "Overline 3",
    variant: "overline-3",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "+8%",
    notes: "UPPERCASE",
  },
  // Label
  {
    id: "label-1",
    category: "Label",
    name: "Label 1",
    variant: "label-1",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
  },
  {
    id: "label-2",
    category: "Label",
    name: "Label 2",
    variant: "label-2",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
  },
  {
    id: "label-3",
    category: "Label",
    name: "Label 3",
    variant: "label-3",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
  },
  {
    id: "label-4",
    category: "Label",
    name: "Label 4",
    variant: "label-4",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
  },
  // Link
  {
    id: "link-1",
    category: "Link",
    name: "Link 1",
    variant: "link-1",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
    notes: "Underline",
  },
  {
    id: "link-2",
    category: "Link",
    name: "Link 2",
    variant: "link-2",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
    notes: "Underline",
  },
  {
    id: "link-3",
    category: "Link",
    name: "Link 3",
    variant: "link-3",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
    notes: "Underline",
  },
  {
    id: "link-4",
    category: "Link",
    name: "Link 4",
    variant: "link-4",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
    notes: "Underline",
  },
  {
    id: "link-5",
    category: "Link",
    name: "Link 5",
    variant: "link-5",
    family: "Geist",
    weightLabel: "SemiBold (600)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
    notes: "Underline",
  },
  // Mono
  {
    id: "mono-1-bold",
    category: "Mono",
    name: "Mono 1 / Bold",
    variant: "mono-1",
    weight: "bold",
    family: "Google Sans Code",
    weightLabel: "Bold (700)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-1-semibold",
    category: "Mono",
    name: "Mono 1 / Semi Bold",
    variant: "mono-1",
    weight: "semibold",
    family: "Google Sans Code",
    weightLabel: "SemiBold (600)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-1-regular",
    category: "Mono",
    name: "Mono 1 / Regular",
    variant: "mono-1",
    weight: "regular",
    family: "Google Sans Code",
    weightLabel: "Regular (400)",
    size: "18px",
    lineHeight: "28px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-2-bold",
    category: "Mono",
    name: "Mono 2 / Bold",
    variant: "mono-2",
    weight: "bold",
    family: "Google Sans Code",
    weightLabel: "Bold (700)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-2-semibold",
    category: "Mono",
    name: "Mono 2 / Semi Bold",
    variant: "mono-2",
    weight: "semibold",
    family: "Google Sans Code",
    weightLabel: "SemiBold (600)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-2-regular",
    category: "Mono",
    name: "Mono 2 / Regular",
    variant: "mono-2",
    weight: "regular",
    family: "Google Sans Code",
    weightLabel: "Regular (400)",
    size: "16px",
    lineHeight: "24px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-3-bold",
    category: "Mono",
    name: "Mono 3 / Bold",
    variant: "mono-3",
    weight: "bold",
    family: "Google Sans Code",
    weightLabel: "Bold (700)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-3-semibold",
    category: "Mono",
    name: "Mono 3 / Semi Bold",
    variant: "mono-3",
    weight: "semibold",
    family: "Google Sans Code",
    weightLabel: "SemiBold (600)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-3-regular",
    category: "Mono",
    name: "Mono 3 / Regular",
    variant: "mono-3",
    weight: "regular",
    family: "Google Sans Code",
    weightLabel: "Regular (400)",
    size: "14px",
    lineHeight: "22px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-4-bold",
    category: "Mono",
    name: "Mono 4 / Bold",
    variant: "mono-4",
    weight: "bold",
    family: "Google Sans Code",
    weightLabel: "Bold (700)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-4-semibold",
    category: "Mono",
    name: "Mono 4 / Semi Bold",
    variant: "mono-4",
    weight: "semibold",
    family: "Google Sans Code",
    weightLabel: "SemiBold (600)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-4-regular",
    category: "Mono",
    name: "Mono 4 / Regular",
    variant: "mono-4",
    weight: "regular",
    family: "Google Sans Code",
    weightLabel: "Regular (400)",
    size: "12px",
    lineHeight: "18px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-5-bold",
    category: "Mono",
    name: "Mono 5 / Bold",
    variant: "mono-5",
    weight: "bold",
    family: "Google Sans Code",
    weightLabel: "Bold (700)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-5-semibold",
    category: "Mono",
    name: "Mono 5 / Semi Bold",
    variant: "mono-5",
    weight: "semibold",
    family: "Google Sans Code",
    weightLabel: "SemiBold (600)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
    notes: "Labs only",
  },
  {
    id: "mono-5-regular",
    category: "Mono",
    name: "Mono 5 / Regular",
    variant: "mono-5",
    weight: "regular",
    family: "Google Sans Code",
    weightLabel: "Regular (400)",
    size: "10px",
    lineHeight: "16px",
    letterSpacing: "0",
    notes: "Labs only",
  },
];

export const TYPOGRAPHY_CATEGORIES = [
  "Heading",
  "Body",
  "Overline",
  "Label",
  "Link",
  "Mono",
] as const;

export interface TypographyStyleGroup {
  key: string;
  category: string;
  /** Short label for the card (e.g. "Heading 1", "Body 3", "Overline 2"). */
  label: string;
  specimens: TypographySpecimen[];
}

/** Group weight variants of the same style into one catalog card. */
export function groupSpecimensByStyle(
  specimens: TypographySpecimen[],
): TypographyStyleGroup[] {
  const groups: TypographyStyleGroup[] = [];
  const byVariant = new Map<string, TypographyStyleGroup>();

  for (const specimen of specimens) {
    const existing = byVariant.get(specimen.variant);
    if (existing) {
      existing.specimens.push(specimen);
      continue;
    }

    const group: TypographyStyleGroup = {
      key: specimen.variant,
      category: specimen.category,
      label: styleGroupLabel(specimen),
      specimens: [specimen],
    };
    byVariant.set(specimen.variant, group);
    groups.push(group);
  }

  return groups;
}

function styleGroupLabel(specimen: TypographySpecimen): string {
  const slash = specimen.name.indexOf(" / ");
  if (slash === -1) return specimen.name;
  return specimen.name.slice(0, slash);
}
