import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { colorSystemToCssVarBlock } from "./colorSystemToCss.mjs";

const ROOT_DIR = process.cwd();

const CODEAI_COLOR_SYSTEM_PATH = path.join(
  ROOT_DIR,
  "src",
  "pages",
  "design-system",
  "tokens",
  "codeAiColorSystem.json",
);

const OUTPUT_PATH = path.join(ROOT_DIR, "src", "styles", "tokens.css");

/**
 * Hand-maintained syntax highlighting palette (not semantic UI roles).
 * Tones sit near CodeAI brand/accent hues for familiarity, but prioritize
 * contrast and role separation over strict token reuse.
 */
const SYNTAX_LIGHT = `  --ds-syntax-attribute: #B34800;
  --ds-syntax-comment: #69788A;
  --ds-syntax-keyword: #4C42CF;
  --ds-syntax-number: #0B43A3;
  --ds-syntax-property: #B5004F;
  --ds-syntax-punctuation: #596069;
  --ds-syntax-selector: #1A7F85;
  --ds-syntax-string: #1F7028;
  --ds-syntax-tag: #3228B7;
  --ds-syntax-value: #1570D1;`;

const SYNTAX_DARK = `  --ds-syntax-attribute: #FFA868;
  --ds-syntax-comment: #87909A;
  --ds-syntax-keyword: #ACA8EA;
  --ds-syntax-number: #94D7FF;
  --ds-syntax-property: #F07FB0;
  --ds-syntax-punctuation: #B7BCC2;
  --ds-syntax-selector: #56B6C2;
  --ds-syntax-string: #7CDB87;
  --ds-syntax-tag: #6F67D9;
  --ds-syntax-value: #61AFEF;`;

function loadCodeAiColorSystem() {
  if (!fs.existsSync(CODEAI_COLOR_SYSTEM_PATH)) {
    throw new Error(
      `CodeAI ColorSystem not found at ${CODEAI_COLOR_SYSTEM_PATH}`,
    );
  }
  return JSON.parse(fs.readFileSync(CODEAI_COLOR_SYSTEM_PATH, "utf-8"));
}

function buildCss(codeAiSystem) {
  const lightBlock = colorSystemToCssVarBlock(codeAiSystem, "light");
  const darkBlock = colorSystemToCssVarBlock(codeAiSystem, "dark");

  return `/* Auto-generated by scripts/generate-tokens.mjs. Do not edit manually.
 * Source: src/pages/design-system/tokens/codeAiColorSystem.json
 * Naming synced with colorSystemCssExport.ts (semanticExportVarName).
 */
:root {
${lightBlock}
${SYNTAX_LIGHT}
}

.dark {
${darkBlock}
${SYNTAX_DARK}
}
`;
}

const codeAiSystem = loadCodeAiColorSystem();
const css = buildCss(codeAiSystem);

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, css, "utf-8");

console.log(`Generated token CSS: ${OUTPUT_PATH}`);
