import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { colorSystemToCssVarBlock } from "./colorSystemToCss.mjs";

const ROOT_DIR = process.cwd();

const CODEAI_COLOR_SYSTEM_PATH = path.join(
  ROOT_DIR,
  "src",
  "pages",
  "design-system",
  "tokens",
  "codeAiColorSystem.json",
);

const OUTPUT_PATH = path.join(ROOT_DIR, "src", "styles", "tokens.css");

/**
 * Hand-maintained syntax highlighting palette until CodeAI defines one.
 * Carried forward from the previous Code.org token blocks.
 */
const SYNTAX_LIGHT = `  --ds-syntax-attribute: #945F10;
  --ds-syntax-comment: #6A737D;
  --ds-syntax-keyword: #7C3AED;
  --ds-syntax-number: #0550AE;
  --ds-syntax-property: #BE3030;
  --ds-syntax-punctuation: #5C6370;
  --ds-syntax-selector: #1A7F85;
  --ds-syntax-string: #22753F;
  --ds-syntax-tag: #BE3030;
  --ds-syntax-value: #0550AE;`;

const SYNTAX_DARK = `  --ds-syntax-attribute: #D19A66;
  --ds-syntax-comment: #7F848E;
  --ds-syntax-keyword: #C678DD;
  --ds-syntax-number: #61AFEF;
  --ds-syntax-property: #E06C75;
  --ds-syntax-punctuation: #ABB2BF;
  --ds-syntax-selector: #56B6C2;
  --ds-syntax-string: #98C379;
  --ds-syntax-tag: #E06C75;
  --ds-syntax-value: #61AFEF;`;

function loadCodeAiColorSystem() {
  if (!fs.existsSync(CODEAI_COLOR_SYSTEM_PATH)) {
    throw new Error(
      `CodeAI ColorSystem not found at ${CODEAI_COLOR_SYSTEM_PATH}`,
    );
  }
  return JSON.parse(fs.readFileSync(CODEAI_COLOR_SYSTEM_PATH, "utf-8"));
}

function buildCss(codeAiSystem) {
  const lightBlock = colorSystemToCssVarBlock(codeAiSystem, "light");
  const darkBlock = colorSystemToCssVarBlock(codeAiSystem, "dark");

  return `/* Auto-generated by scripts/generate-tokens.mjs. Do not edit manually.
 * Source: src/pages/design-system/tokens/codeAiColorSystem.json
 * Naming synced with colorSystemCssExport.ts (semanticExportVarName).
 */
:root {
${lightBlock}
${SYNTAX_LIGHT}
}

.dark {
${darkBlock}
${SYNTAX_DARK}
}
`;
}

const codeAiSystem = loadCodeAiColorSystem();
const css = buildCss(codeAiSystem);

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, css, "utf-8");

console.log(`Generated token CSS: ${OUTPUT_PATH}`);
