import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const ROOT_DIR = process.cwd();
const DEFAULT_LIGHT_PATH =
  "/Users/MosheFrost/Desktop/Semantic Colors/Light.tokens.json";
const DEFAULT_DARK_PATH =
  "/Users/MosheFrost/Desktop/Semantic Colors/Dark.tokens.json";

const LIGHT_PATH =
  process.env.WL2_LIGHT_TOKENS_PATH ??
  path.join(ROOT_DIR, "tokens", "semantic", "light.tokens.json");
const DARK_PATH =
  process.env.WL2_DARK_TOKENS_PATH ??
  path.join(ROOT_DIR, "tokens", "semantic", "dark.tokens.json");

const OUTPUT_PATH = path.join(ROOT_DIR, "src", "styles", "tokens.css");

function readJson(tokenPath, fallbackPath) {
  if (fs.existsSync(tokenPath)) {
    return JSON.parse(fs.readFileSync(tokenPath, "utf-8"));
  }
  if (fs.existsSync(fallbackPath)) {
    return JSON.parse(fs.readFileSync(fallbackPath, "utf-8"));
  }
  throw new Error(
    `Token file not found. Checked: ${tokenPath} and ${fallbackPath}`,
  );
}

function normalizeName(segments) {
  return segments.join("-").replace(/[^a-zA-Z0-9-]/g, "-").toLowerCase();
}

function getNodeAtPath(root, dottedPath) {
  return dottedPath.split(".").reduce((acc, key) => acc?.[key], root);
}

function resolveTokenValue(root, node, stack = new Set()) {
  if (!node || typeof node !== "object") {
    return null;
  }

  const value = node.$value;
  if (typeof value === "string") {
    const match = value.match(/^\{(.+)\}$/);
    if (!match) {
      return null;
    }
    const referencePath = match[1];
    if (stack.has(referencePath)) {
      throw new Error(`Circular token reference detected: ${referencePath}`);
    }
    stack.add(referencePath);
    const targetNode = getNodeAtPath(root, referencePath);
    const resolved = resolveTokenValue(root, targetNode, stack);
    stack.delete(referencePath);
    return resolved;
  }

  if (value && typeof value === "object" && typeof value.hex === "string") {
    return value.hex.toUpperCase();
  }

  return null;
}

function flattenTokens(root, node, segments = [], output = new Map()) {
  if (!node || typeof node !== "object") {
    return output;
  }

  if (node.$type === "color") {
    const resolved = resolveTokenValue(root, node);
    if (resolved) {
      output.set(normalizeName(segments), resolved);
    }
    return output;
  }

  for (const [key, value] of Object.entries(node)) {
    if (key.startsWith("$")) {
      continue;
    }
    flattenTokens(root, value, [...segments, key], output);
  }

  return output;
}

function toCssVars(map) {
  return [...map.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, value]) => `  --ds-${name}: ${value};`)
    .join("\n");
}

function buildCss(lightTokens, darkTokens) {
  return `/* Auto-generated by scripts/generate-tokens.mjs. Do not edit manually. */
:root {
${toCssVars(lightTokens)}
}

.dark {
${toCssVars(darkTokens)}
}
`;
}

const lightSemantic = readJson(
  LIGHT_PATH,
  DEFAULT_LIGHT_PATH,
);
const darkSemantic = readJson(
  DARK_PATH,
  DEFAULT_DARK_PATH,
);

const lightMap = flattenTokens(lightSemantic, lightSemantic);
const darkMap = flattenTokens(darkSemantic, darkSemantic);
const css = buildCss(lightMap, darkMap);

fs.mkdirSync(path.dirname(OUTPUT_PATH), { recursive: true });
fs.writeFileSync(OUTPUT_PATH, css, "utf-8");

console.log(`Generated token CSS: ${OUTPUT_PATH}`);
